### ISSUE TITLE
Scala representation

### ISSUE THREAD

**Issue by bechang** [Athithyaa/WalaTest#3]
Please use a Scala representation for your constants domain. Please use an algebraic data type (i.e., case classes in Scala) to represent the constants domain: ⊤, ⊥, n. And then, use a Scala `Map` to represent an analysis state mapping variables to an element of the constants domain.

**Comment by Athithyaa** [comment]
@bechang I have used a string representation for the constant domain. Using a Scala based case class representation for constant domain would affect a major part of the code and also the java implementation. This is because of the fact that the EdgeManager class which is used to map variables to the edges in the control flow graph uses a string based representation. Also the EdgeManager class is shared by Java and Scala. I will try to come up with something else to demonstrate my understand on case classes.
